import { CLUSTER_PRIMARY_PILL_WIDTH } from '../../cluster/constants';
import { CLUSTER_PILL_HEIGHT } from '../../cluster/constants';

export const {
    CLUSTER_MERGE_LAT_FACTOR,
    CLUSTER_MERGE_LNG_FACTOR,
    CLUSTER_SPLIT_MULTIPLIER,
} = require('../../lib/clusterAnimationMath.cjs');

export const {
    MIN_PREFETCH_SPEED_MPS,
    buildTrajectorySeedFromLocationObject,
} = require('../../lib/trajectoryFuelFetch.js');

export const DEFAULT_REGION = {
    latitude: 37.3346,
    longitude: -122.009,
    latitudeDelta: 0.05,
    longitudeDelta: 0.05,
};

export const TAB_BAR_CLEARANCE = 34;

export const CARD_GAP = 0;

export const SIDE_MARGIN = 12;

export const TOP_CANOPY_HEIGHT = 72;

export const CLUSTER_DEBUG_JUMP_THRESHOLD = 5;

export const MAP_REGION_EPSILON = 0.000001;

export const CLUSTER_DEBUG_PROBE_ANIMATION_DURATION = 650;

export const CLUSTER_DEBUG_PROBE_IDLE_TIMEOUT = 2400;

export const CLUSTER_DEBUG_PROBE_SETTLE_DURATION = 180;

export const CLUSTER_MAP_IDLE_SETTLE_MS = 600;

export const CLUSTER_DEBUG_PROBE_INITIAL_LOAD_WAIT = 3000;

export const CLUSTER_DEBUG_PROBE_RECORDING_DELAY = 150;

export const CLUSTER_DEBUG_PROBE_ZOOM_IN_STEP_COUNT = 10;

export const CLUSTER_DEBUG_PROBE_ZOOM_OUT_EXTRA_STEPS = 5;

export const CLUSTER_DEBUG_PROBE_BETWEEN_STEP_DELAY = 100;

export const CLUSTER_DEBUG_PROBE_ZOOM_IN_DISTANCE_MULTIPLIER = 1.3;

export const CLUSTER_DEBUG_PROBE_ZOOM_OUT_DISTANCE_MULTIPLIER = 1.3;

export const CLUSTER_DEBUG_PROBE_MIN_DELTA = 0.0005;

export const CLUSTER_DEBUG_PROBE_REPORT_FILE_NAME = 'cluster-debug-probe.json';

export const CLUSTER_DEBUG_PROBE_REPORT_RELATIVE_PATH = `Documents/${CLUSTER_DEBUG_PROBE_REPORT_FILE_NAME}`;

export const CLUSTER_DEBUG_PROBE_REPORT_CACHE_RELATIVE_PATH = `Library/Caches/${CLUSTER_DEBUG_PROBE_REPORT_FILE_NAME}`;

export const USER_LOCATION_BUBBLE_SIZE = 14;

export const USER_LOCATION_OVERLAP_PILL_WIDTH = CLUSTER_PRIMARY_PILL_WIDTH - 28;

export const USER_LOCATION_OVERLAP_PILL_HEIGHT = CLUSTER_PILL_HEIGHT - 14;

export const SUPPRESSION_REVEAL_PADDING = 10;


export const STATION_FOCUS_MIN_LATITUDE_DELTA = 0.002;

export const STATION_FOCUS_MIN_LONGITUDE_DELTA = 0.002;

export const STATION_FOCUS_ZOOM_STEP_MULTIPLIER = 0.82;

export const STATION_FOCUS_MAX_STEPS = 18;

export const STATION_FOCUS_ANIMATION_MS = 420;

export const FOREGROUND_RECENTER_ANIMATION_MS = 420;

export const STATIONS_FIT_TOP_EXTRA_PADDING = 16;

export const STATIONS_FIT_BOTTOM_CONTENT_PADDING = 140;

export const STATIONS_FIT_SIDE_EXTRA_PADDING = 12;

export const STATIONS_FIT_SETTLE_PASS_DELAY_MS = 260;

export const STATIONS_FIT_UPWARD_BIAS_FACTOR = 0.03;

export const INITIAL_HOME_SUPPRESSION_DELAY_MS = 900;

export const INITIAL_STATIONS_FIT_MAX_ATTEMPTS = 4;

export const INITIAL_STATIONS_FIT_RETRY_DELAY_MS = 120;

export const INITIAL_SMOOTH_LAUNCH_TRANSITION_MAX_DISTANCE_METERS = 6000;

export const LAUNCH_MOVEMENT_RECOVERY_TIMEOUT_MS = 5000;

export const ENABLE_CLUSTER_MERGE_TRANSITIONS = false;

export const HOME_DARK_GLASS_TINT = '#373737ff';

export const TRACKING_IDLE_GRACE_MS = 3000;

export const LIVE_TRACKING_DISTANCE_INTERVAL_METERS = 10;

export const LIVE_TRACKING_PAN_SUPPRESS_MS = 10_000;

export const LIVE_TRACKING_STATE_UPDATE_METERS = 50;

export const LIVE_TRACKING_REFETCH_MIN_INTERVAL_MS = 1500;

export const LIVE_TRACKING_TRAJECTORY_MIN_SPEED_MPS = MIN_PREFETCH_SPEED_MPS;
