// Deno and Metro use identical pure provider/validation logic. No runtime deps.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
for (const name of ['core', 'priceValidation', 'stationData', 'reportedPrices']) {
    let source = fs.readFileSync(path.join(root, 'src/services/fuel', `${name}.js`), 'utf8');
    source = source.replace(/const (\{[^;]+?\}) = require\('\.\/(\w+)'\);/g, 'import $1 from "./$2.mjs";');
    source = source.replace('module.exports = {', 'export {');
    if (/require\(|module\.exports/.test(source)) throw new Error(`Unexpected dependency in ${name}`);
    const output = '// Generated by scripts/buildFuelFunctionShared.cjs. Edit src/services/fuel instead.\n' + source;
    const target = path.join(root, 'supabase/functions/_shared', `${name}.mjs`);
    if (process.argv.includes('--check')) {
        if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== output) throw new Error(`Stale generated file: ${name}`);
    } else fs.writeFileSync(target, output);
}
